# Generated by Django 3.0.7 on 2021-07-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tag',
            field=models.CharField(choices=[('trending', 'trending'), ('latest', 'latest'), ('editor1', 'editor1'), ('editor2', 'editor2'), ('popular', 'popular')], default='latest', max_length=100),
        ),
    ]
