# Generated by Django 3.0.7 on 2021-07-26 04:17

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appdashboard', '0002_auto_20210725_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tag',
            field=models.CharField(choices=[('trending_first', 'trending_first'), ('trending', 'trending'), ('latest', 'latest'), ('editor1', 'editor1'), ('editor2', 'editor2'), ('popular', 'popular')], default='latest', max_length=100),
        ),
    ]
